HallOfFame/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path
from halls import views

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', views.home, name='home'),
    path('dashboard', views.dashboard, name='dashboard'),
    # AUTH
    path('signup', views.SignUp.as_view(), name='signup'),
    path('login', auth_views.LoginView.as_view(), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    # Halls
    path('halloffame/create', views.CreateHall.as_view(), name='create_hall'),
    path('halloffame/<int:pk>', views.DetailHall.as_view(), name='detail_hall'),
    path('halloffame/<int:pk>/update', views.UpdateHall.as_view(), name='update_hall'),
    path('halloffame/<int:pk>/delete', views.DeleteHall.as_view(), name='delete_hall'),
    # Videos
    path('halloffame/<int:pk>/add_video', views.add_video, name='video_search'),
    path('video/search', views.video_search, name='add_video'),
    path('video/<int:pk>/delete', views.DeleteVideo.as_view(), name='delete_video'),
    # Сброс пароля
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='password_reset/form.html',
                                              html_email_template_name='password_reset/email.html',
                                              subject_template_name='password_reset/subject_email.txt'),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='password_reset/done.html'),
         name='password_reset_done'),
    path('password-reset/confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='password_reset/confirm.html'),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/complete.html'),
         name='password_reset_complete'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

halls/models.py
from django.db import models
from django.contrib.auth.models import User


class Hall(models.Model):
    title = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Video(models.Model):
    title = models.CharField(max_length=255)
    url = models.URLField()
    youtube_id = models.CharField(max_length=255)
    hall = models.ForeignKey(Hall, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

halls/forms.py
from .models import Video
from django import forms


class VideoForm(forms.ModelForm):
    class Meta:
        model = Video
        fields = ['url']
        labels = {'url': 'YouTube URL'}


class SearchForm(forms.Form):
    search_term = forms.CharField(max_length=255, label='Найти видео')

halls/views.py
from django.http import Http404, JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.forms import UserCreationForm
from .models import Hall, Video
from django.contrib.auth import authenticate, login
from .forms import VideoForm, SearchForm
import urllib
import requests
from django.forms.utils import ErrorList
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin  # Проверка, авторизован ли пользователь

YOUTUBE_API_KEY = 'AIzaSyA7me2LhTLRNxT8QYFEqpsarNnFyhNvxSM'


def home(request):
    recent_halls = Hall.objects.all().order_by('-id')[:3]
    popular_halls = Hall.objects.all()[:4]
    return render(request, 'halls/home.html', {'popular_halls': popular_halls, 'recent_halls': recent_halls})


@login_required
def dashboard(request):
    halls = Hall.objects.filter(user=request.user).order_by('-id')
    return render(request, 'halls/dashboard.html', {'halls': halls})


@login_required
def video_search(request):
    search_form = SearchForm(request.GET)
    if search_form.is_valid():
        encoded_search_term = urllib.parse.quote(search_form.cleaned_data['search_term'])
        response = requests.get(
            f'https://www.googleapis.com/youtube/v3/search?part=snippet&maxResults=6&q={encoded_search_term}&key={YOUTUBE_API_KEY}')
        return JsonResponse(response.json())
    return JsonResponse({'error': 'Not able to validate form'})


@login_required
def add_video(request, pk):
    form = VideoForm()
    search_form = SearchForm()
    hall = Hall.objects.get(pk=pk)
    if not hall.user == request.user:
        raise Http404
    if request.method == 'POST':
        form = VideoForm(request.POST)
        if form.is_valid():
            video = Video()
            video.hall = hall
            video.url = form.cleaned_data['url']
            parsed_url = urllib.parse.urlparse(video.url)
            video_id = urllib.parse.parse_qs(parsed_url.query).get('v')
            if video_id:
                video_id = video_id[0].strip("/")
                video.youtube_id = video_id
                response = requests.get(
                    f'https://youtube.googleapis.com/youtube/v3/videos?part=snippet&id={video.youtube_id}&key={YOUTUBE_API_KEY}')
                json = response.json()
                print(json)
                title = json['items'][0]['snippet']['title']
                video.title = title
                video.save()
                return redirect('detail_hall', pk)
            else:
                errors = form._errors.setdefault('url', ErrorList())
                errors.append('Некорректный URL')

    return render(request, 'halls/add_video.html', {'form': form, 'search_form': search_form, 'hall': hall})


class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('dashboard')
    template_name = 'registration/signup.html'

    # Автоматический вход в систему после регистрации
    def form_valid(self, form):
        view = super(SignUp, self).form_valid(form)
        username, password = form.cleaned_data.get('username'), form.cleaned_data.get('password1')
        user = authenticate(username=username, password=password)
        login(self.request, user)
        return view


'''
ПРЕДСТАВЛЕНИЕ НА ОСНОВЕ ФУНКЦИЙ
def create_hall(request):
   if request.method == 'POST':
        #get the form data
        #valide form data
        #create Hall
        #save Hall
   else:
       #Create a form a hall
        #return the template
'''

'''ПРЕДСТАВЛЕНИЕ НА ОСНОВЕ КЛАССОВ'''


class CreateHall(LoginRequiredMixin, generic.CreateView):
    model = Hall
    fields = ['title']
    template_name = 'halls/create_hall.html'
    success_url = reverse_lazy('dashboard')

    def form_valid(self, form):
        form.instance.user = self.request.user
        super(CreateHall, self).form_valid(form)
        return redirect('dashboard')


class DetailHall(generic.DetailView):
    model = Hall
    template_name = 'halls/detail_hall.html'


class UpdateHall(LoginRequiredMixin, generic.UpdateView):
    model = Hall
    template_name = 'halls/update_hall.html'
    # В Update передаем поля(fields) для обновления
    fields = ['title']
    success_url = reverse_lazy('dashboard')

    # Функция позволяющая обновлять Зал Славы только добавившему его пользователю
    def get_object(self):
        hall = super(UpdateHall, self).get_object()
        if not hall.user == self.request.user:
            raise Http404
        return hall


class DeleteHall(LoginRequiredMixin, generic.DeleteView):
    model = Hall
    template_name = 'halls/delete_hall.html'
    success_url = reverse_lazy('dashboard')

    def get_object(self):
        hall = super(DeleteHall, self).get_object()
        if not hall.user == self.request.user:
            raise Http404
        return hall


class DeleteVideo(LoginRequiredMixin, generic.DeleteView):
    model = Video
    template_name = 'halls/delete_video.html'
    success_url = reverse_lazy('dashboard')

    # Функция позволяющая удалять видео только добавившему его пользователю
    def get_object(self):
        video = super(DeleteVideo, self).get_object()
        if not video.hall.user == self.request.user:
            raise Http404
        return video

templates/base.html
<!doctype html>
<html lang="en">
{% load static %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Hall Of Fame</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link href={% static 'custom.css' %} rel="stylesheet">
    <link rel="shortcut icon" type="image/png" href={% static 'favicon.ico' %}/>
</head>

<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 bg-white border-bottom shadow-sm">
    <h5 class="my-0 mr-md-auto font-weight-normal"><a href="{% url 'home' %}" class="text-dark">Зал Славы</a></h5>
    <nav class="my-2 my-md-0 mr-md-3">
        <h7><strong>{{ user.username }}</strong> |</h7>
        <a class="p-2 text-dark" href="{% url 'admin:index' %}">Админка</a>
        {% if user.is_authenticated %}
            <a class="p-2 text-dark" href="{% url 'dashboard' %}">Панель управления</a>
            <a class="p-2 text-dark" href="{% url 'logout' %}">Выход</a>
        {% else %}
            <a class="p-2 text-dark" href="{% url 'login' %}">Вход</a>
        {% endif %}
    </nav>
    {% if user.is_authenticated == False %}
        <a class="btn btn-outline-primary" href="{% url 'signup' %}">Регистрация</a>
    {% endif %}
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
{% block content %}
{% endblock %}

</body>

</html>

templates/halls/add_video.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <h2>Добавьте видео в зал {{ hall.title }}</h2>
        <form method="post" id="submit_video">
            {% csrf_token %}
            {% load widget_tweaks %}

            {% for field in form %}
                <div class="form-group {% if field.errors %}alert alert-danger{% endif %}">
                    {{ field.errors }}
                    {{ field.label_tag }}
                    {% render_field field class="form-control" %}
                </div>
            {% endfor %}

            <button type="submit" class="btn btn-primary">Добавить</button>
        </form>
        <br>
        <h2>Или</h2>
        <form>
            {% for field in search_form %}
                <div class="form-group">
                    {{ field.errors }}
                    {{ field.label_tag }}
                    {% render_field field class="form-control" %}
                </div>
            {% endfor %}
        </form>

        <div id="search_results"></div>
        <script>
            var delayTimer;
            $('#id_search_term').keyup(function () {
                clearTimeout(delayTimer);
                $('#search_results').text('Загрузка...');
                delayTimer = setTimeout(function () {
                    var text = $('#id_search_term').val();
                    $.ajax({
                        url: '/video/search',
                        data: {
                            'search_term': text
                        },
                        dataType: 'json',
                        success: function (data) {
                            var results = '';
                            $('#search_results').text('');
                            results += '<div class="row">';
                            data['items'].forEach(function (video) {
                                results += '<div class="col-md-4 mt-3"><div class="card mb-4 shadow-sm">';
                                results += '<iframe width="100%" height="225" src="https://www.youtube.com/embed/' + video['id']['videoId'] +
                                    '" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>';
                                results += '<div class="card-body"><p class="card-text">' + video['snippet']['title'] + '</p>';
                                results += '<a href="#" class="btn btn-primary" onclick="addVideo(\'' + video['id']['videoId'] + '\')">Добавить</a></div></div></div>';

                            });
                            results += '</div>';
                            $('#search_results').append(results);
                        }
                    });
                }, 400);
            });

            function addVideo(video_id) {
                $('#id_url').val('https://www.youtube.com/watch?v=' + video_id);
                $('#submit_video').submit();
            }
        </script>

    </div>
{% endblock %}

templates/halls/create_hall.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <h2>Создайте зал славы</h2>
        <form method="post">
        {% csrf_token %}
            {% load widget_tweaks %}
            {% for field in form %}
                <div class="form-group {% if field.errors %}alert alert-danger{% endif %}">
                    {{ field.errors }}
                    {{ field.label_tag }}
                    {% render_field field class="form-control" %}
                </div>
            {% endfor %}
        <button type="submit" class="btn btn-primary">Создать</button>
        </form>
    </div>
{% endblock %}

templates/halls/dashboard.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <div class="text-center">
            <h1>Залы славы пользователя: {{ user.username }}</h1>
            <a href="{% url 'create_hall' %}" class="btn btn-primary">Создать новый зал славы</a>
        </div>

        {% for hall in  halls %}
            <h2><a href="{% url 'detail_hall' hall.id %}">{{ hall.title }}</a></h2>
            <a href="#" class="btn btn-primary">Добавить видео</a>
            <a href="{% url 'update_hall' hall.id %}" class="btn btn-primary">Изменить</a>
            <a href="{% url 'delete_hall' hall.id %}" class="btn btn-danger">Удалить</a>
            <div class="row">
                {% for video in  hall.video_set.all %}
                    <div class="col-md-4 mt-3">
                        <div class="card mb-4 shadow-sm">
                            <iframe width="100%" height="225" src="https://www.youtube.com/embed/{{ video.youtube_id }}"
                                    frameborder="0"
                                    allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                                    allowfullscreen></iframe>
                            <div class="card-body"><p class="card-text"> {{ video.title }}</p></div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% endfor %}

    </div>
{% endblock %}

templates/halls/delete_hall.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <h2>Вы уверены, что хотите удалить этот зал славы?</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <h2><a href="{% url 'detail_hall' hall.id %}" >{{ hall.title }}</a></h2>
            <button type="submit" class="btn btn-danger">Удалить</button>
        </form>

    </div>
{% endblock %}

templates/halls/delete_video.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <h2>Вы уверены, что хотите удалить это видео</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-danger">Удалить</button>
        </form>

        <div class="row">
            <div class="col-md-4 mt-3">
                <div class="card mb-4 shadow-sm">
                    <iframe width="100%" height="225" src="https://www.youtube.com/embed/{{ video.youtube_id }}"
                            frameborder="0"
                            allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                            allowfullscreen></iframe>
                    <div class="card-body"><p class="card-text"> {{ video.title }}</p></div>
                </div>
            </div>
        </div>
    </div>
    </div>
    </div>
{% endblock %}

templates/halls/detail_hall.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <h1>{{ hall.title }}</h1>
        <h4 class="text-muted">Автор: {{ hall.user.username }}</h4>
        {% if user.id == hall.user.id %}
            <a href="#" class="btn btn-primary">Добавить видео</a>
            <a href="{% url 'update_hall' hall.id %}" class="btn btn-primary">Изменить</a>
            <a href="{% url 'delete_hall' hall.id %}" class="btn btn-danger">Удалить</a>
        {% endif %}
        <div class="row">
            {% for video in  hall.video_set.all %}
                <div class="col-md-4 mt-3">
                    <div class="card mb-4 shadow-sm">
                        <iframe width="100%" height="225" src="https://www.youtube.com/embed/{{ video.youtube_id }}"
                                frameborder="0"
                                allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                                allowfullscreen></iframe>
                        <div class="card-body"><p class="card-text"> {{ video.title }}</p>
                            {% if user.id == hall.user.id %}
                                <a href="{% url 'delete_video' video.id %}" class="btn btn-danger">Удалить</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/halls/home.html
{% extends 'base.html' %}
{% block content %}
    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">Какой твой личный Зал Славы?</h1>
            <p class="lead text-muted">
                Ты знаешь какой! У тебя есть топ 10 любимых видео и пора поделиться ими со всем миром. Нажми на кнопку
                что бы начать.
            </p>
            <a href="{% url 'create_hall' %}" class="btn btn-primary">Создать свой Зал славы</a>
            </p>
        </div>
    </section>
    <div class="container">
        <h1 class="text-center">Недавно добавленные Залы Славы</h1>
        {% for hall in  recent_halls %}
            <h2><a href="{% url 'detail_hall' hall.id %}">{{ hall.title }}</a></h2>
            <div class="row">
                {% for video in  hall.video_set.all %}
                    <div class="col-md-4 mt-3">
                        <div class="card mb-4 shadow-sm">
                            <iframe width="100%" height="225" src="https://www.youtube.com/embed/{{ video.youtube_id }}"
                                    frameborder="0"
                                    allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                                    allowfullscreen></iframe>
                            <div class="card-body"><p class="card-text"> {{ video.title }}</p></div>
                        </div>
                    </div>
                {% endfor %}
                <div class="container"><h5>Автор: {{ hall.user.username }}</h5></div>
            </div>
        {% endfor %}
    <h1 class="text-center">Популярные Залы Славы</h1>
        {% for hall in  popular_halls %}
            <h2><a href="{% url 'detail_hall' hall.id %}">{{ hall.title }}</a></h2>
            <div class="row">
                {% for video in  hall.video_set.all %}
                    <div class="col-md-4 mt-3">
                        <div class="card mb-4 shadow-sm">
                            <iframe width="100%" height="225" src="https://www.youtube.com/embed/{{ video.youtube_id }}"
                                    frameborder="0"
                                    allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                                    allowfullscreen></iframe>
                            <div class="card-body"><p class="card-text"> {{ video.title }}</p></div>
                        </div>
                    </div>
                {% endfor %}
                <div class="container"><h5>Автор: {{ hall.user.username }}</h5></div>
            </div>
        {% endfor %}

    </div>
{% endblock %}

templates/halls/update_hall.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <h2>Редактирование зала славы</h2>
        <form method="post">
        {% csrf_token %}
            {% load widget_tweaks %}
            {% for field in form %}
                <div class="form-group {% if field.errors %}alert alert-danger{% endif %}">
                    {{ field.errors }}
                    {{ field.label_tag }}
                    {% render_field field class="form-control" %}
                </div>
            {% endfor %}
        <button type="submit" class="btn btn-primary">Сохранить</button>
        </form>
    <br>
    <a href="{% url 'delete_hall' hall.id%}" class="btn btn-danger">Удалить</a>
    </div>
{% endblock %}

templates/password_reset/complete.html
{% extends "base.html" %}

{% block title %}Востановление пароля{% endblock %}

{% block content %}
    <h1>Пароль установлен</h1>
    <p>Ваш пароль установлен. Вы можете <a href="{% url "login" %}">войти сейчас</a></p>
{% endblock %}

templates/password_reset/confirm.html
{% extends "base.html" %}

{% block title %}Сбросить пароль{% endblock %}

{% block content %}
    <h1>Востановление пароля</h1>
    {% if validlink %}
        <p>Пожалуйста, введите ваш новый пароль дважды:</p>
        <form  method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Изменить пароль"/></p>
        </form>
    {% else %}
        <p>Ссылка для сброса пароля недействительна. Возможно она уже использовалась. Запросите новый сброс пароля.</p>
    {% endif %}
{% endblock %}

templates/password_reset/done.html
{% extends "base.html" %}

{% block title %}Востановление пароля{% endblock %}

{% block content %}
    <h1>Сбросить пароль</h1>
    <p>Мы отправили вам по электронной почте инструкции по установке пароля.</p>
    <p>Если вы не получили электронное письмо, убедитесь, что вы ввели адрес, на который зарегистрировались.</p>
{% endblock %}

templates/password_reset/email.html
Кто-то попросил сбросить пароль для электронной почты {{ email }}. Перейдите по ссылке ниже:
{{ protocol }}://{{ domain }}{% url "password_reset_confirm" uidb64=uid token=token %}
Ваше имя пользователя, если вы забыли: {{ user.get_username }}

templates/password_reset/form.html
{% extends "base.html" %}

{% block title %}Востановление пароля{% endblock %}

{% block content %}
    <h1>Забыли пароль?</h1>
    <p>Введите свой адрес электронной почты, чтобы получить новый пароль.</p>
    <form  method="post">
        {{ form.as_p }}
        <p><input type="submit" class="btn btn-primary" value="Отправить электронное письмо"></p>
        {% csrf_token %}
    </form>
{% endblock %}